#
# Copyright 2021 Merck & Co., Inc. Kenilworth, NJ, USA.
#
#	Licensed to the Apache Software Foundation (ASF) under one
#	or more contributor license agreements. See the NOTICE file
#	distributed with this work for additional information
#	regarding copyright ownership. The ASF licenses this file
#	to you under the Apache License, Version 2.0 (the
#	"License"); you may not use this file except in compliance
#	with the License. You may obtain a copy of the License at
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
#
#	Unless required by applicable law or agreed to in writing,
#	software distributed under the License is distributed on an
#	"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#	KIND, either express or implied. See the License for the
#	specific language governing permissions and limitations
#	under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-accumulo
  labels:
    app: mini-accumulo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini-accumulo
  template:
    metadata:
      labels:
        app: mini-accumulo
    spec:
      hostname: mini-accumulo
      containers:
      - name: mini-accumulo
        image: dp/accumulo
        imagePullPolicy: Never
        ports:
        - containerPort: 2181
        - containerPort: 9999
        stdin: true
        tty: true
        volumeMounts:
        - name: host-mount
          mountPath: /accumulo-data
      - name: spark-sql-controller
        image: spark-sql-controller
        imagePullPolicy: Never
        ports:
        - containerPort: 10000
        stdin: true
        tty: true
        volumeMounts:
        - name: host-mount
          mountPath: /spark-sql-controller-data
      volumes:
        - hostPath:
            path: /host-data
          name: host-mount
        
