#
# Copyright 2021 Merck & Co., Inc. Kenilworth, NJ, USA.
#
#	Licensed to the Apache Software Foundation (ASF) under one
#	or more contributor license agreements. See the NOTICE file
#	distributed with this work for additional information
#	regarding copyright ownership. The ASF licenses this file
#	to you under the Apache License, Version 2.0 (the
#	"License"); you may not use this file except in compliance
#	with the License. You may obtain a copy of the License at
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
#
#	Unless required by applicable law or agreed to in writing,
#	software distributed under the License is distributed on an
#	"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#	KIND, either express or implied. See the License for the
#	specific language governing permissions and limitations
#	under the License.
#
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.podName }}
    namespace: {{ .Release.Namespace | quote }}
    labels:
        app: {{ .Values.podName }}
spec:
    replicas: {{ .Values.replicas }}
    selector:
      matchLabels:
        app: {{ .Values.podName }}
    template:
        metadata:
          namespace: {{ .Release.Namespace | quote }}
          labels:
            app: {{ .Values.podName }}
        spec:
          containers:
          - name: {{ .Values.podName }}
            image: {{ .Values.image.name | quote }}
            ports:
            - containerPort: {{ .Values.service.targetPort }}
            resources:
              requests:
                memory: {{ .Values.ui.resources.requests.memory | quote }}
                cpu: {{ .Values.ui.resources.requests.cpu | quote }}
              limits:
                memory: {{ .Values.ui.resources.limits.memory | quote }}
                cpu: {{ .Values.ui.resources.limits.cpu | quote }}
            volumeMounts:
              - mountPath: /tmp
                name: dp-ui-tmp-vol
            livenessProbe:
              httpGet:
                path: /
                port: {{ .Values.service.targetPort }}
              failureThreshold: 2
              periodSeconds: 60
              timeoutSeconds: 10
            startupProbe:
              httpGet:
                path: /
                port: {{ .Values.service.targetPort }}
              initialDelaySeconds: 15
              failureThreshold: 5
              periodSeconds: 60
              timeoutSeconds: 10                
          imagePullSecrets:
          - name: {{ .Values.imagePullSecrets | quote }}
          restartPolicy: "Always"
          volumes:
          - name: dp-ui-tmp-vol
            emptyDir: {}
