#
# Copyright 2021 Merck & Co., Inc. Kenilworth, NJ, USA.
#
#	Licensed to the Apache Software Foundation (ASF) under one
#	or more contributor license agreements. See the NOTICE file
#	distributed with this work for additional information
#	regarding copyright ownership. The ASF licenses this file
#	to you under the Apache License, Version 2.0 (the
#	"License"); you may not use this file except in compliance
#	with the License. You may obtain a copy of the License at
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
#
#	Unless required by applicable law or agreed to in writing,
#	software distributed under the License is distributed on an
#	"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#	KIND, either express or implied. See the License for the
#	specific language governing permissions and limitations
#	under the License.
#
apiVersion: v1
kind: Service
metadata:
  name: dp-hadoop-svc-proxy
  namespace: {{ .Release.Namespace | quote }}
spec:
  type: ExternalName
  externalName: accumulo-master-{{ .Release.Namespace }}-1.dataprofiler.com
  ports:
    - port: {{ .Values.hadoopPort }}
      targetPort: {{ .Values.hadoopPort }}
---
kind: Ingress
apiVersion: networking.k8s.io/v1beta1
metadata:
  name: dp-hadoop-svc-proxy
  namespace: {{ .Release.Namespace | quote }}
  annotations:
    # use the shared ingress-nginx
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$2

    # require ldap membership
    nginx.ingress.kubernetes.io/auth-url: http://only-nginx-ldap-auth.ingress-nginx.svc.cluster.local:5555
   
    # Hadoop uses absolute URLs so we need to rewrite the base URL
    nginx.ingress.kubernetes.io/configuration-snippet: |
      sub_filter '<head>' '<head> <base href="/hadoop/">';
      sub_filter "href='/" "href='";
      sub_filter 'href="/' 'href="';
      sub_filter "src='/" "src='";
      sub_filter 'src="/' 'src="';
      sub_filter 'href="#' 'href="dfshealth.html#';
      sub_filter '/jmx?qry' '/hadoop/jmx?qry';
      sub_filter '/startupProgress' '/hadoop/startupProgress';
      sub_filter_once off;
      sub_filter_types *;

spec:
  rules:
  - host: {{ required "A valid .values.loadBalancer entry required!" .Values.loadBalancer }}
    http:
      paths:
      - backend:
          serviceName: dp-hadoop-svc-proxy
          servicePort: {{ .Values.hadoopPort }}
        path: /hadoop(/|$)(.*)
