#
# Copyright 2021 Merck & Co., Inc. Kenilworth, NJ, USA.
#
#	Licensed to the Apache Software Foundation (ASF) under one
#	or more contributor license agreements. See the NOTICE file
#	distributed with this work for additional information
#	regarding copyright ownership. The ASF licenses this file
#	to you under the Apache License, Version 2.0 (the
#	"License"); you may not use this file except in compliance
#	with the License. You may obtain a copy of the License at
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
#
#	Unless required by applicable law or agreed to in writing,
#	software distributed under the License is distributed on an
#	"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#	KIND, either express or implied. See the License for the
#	specific language governing permissions and limitations
#	under the License.
#
---
- name: start spark master services
  service:
    name: spark-{{ item }}
    state: started
  loop:
    - master
    - history-server
  when: "'spark_masters' in group_names"
  tags: [ spark, spark_master_services ]

- name: start spark primary master
  service:
    name: spark-master
    state: started
  when: "'spark_master' in group_names"
  tags: [ never, spark_master, spark_primary_master ]

- name: start spark workers
  service:
    name: spark-{{ item }}
    state: started
  loop:
    - slave
    - shuffle-service
  when: "'spark_workers' in group_names"
  tags: [ spark, spark_workers ]

- name: start spark history server
  service:
    name: spark-history-server
    state: started
  when: "'spark_master' in group_names"
  tags: [ never, spark_history_server ]

- name: start spark shuffle services
  service:
    name: spark-shuffle-service
    state: started
  when: "'spark_workers' in group_names"
  tags: [ never, spark_shuffle_service ]