#
# Copyright 2021 Merck & Co., Inc. Kenilworth, NJ, USA.
#
#	Licensed to the Apache Software Foundation (ASF) under one
#	or more contributor license agreements. See the NOTICE file
#	distributed with this work for additional information
#	regarding copyright ownership. The ASF licenses this file
#	to you under the Apache License, Version 2.0 (the
#	"License"); you may not use this file except in compliance
#	with the License. You may obtain a copy of the License at
#
#	http://www.apache.org/licenses/LICENSE-2.0
#
#
#	Unless required by applicable law or agreed to in writing,
#	software distributed under the License is distributed on an
#	"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#	KIND, either express or implied. See the License for the
#	specific language governing permissions and limitations
#	under the License.
#
- name: Install default packages
  apt:
    name: "{{ packages }}"
    state: latest
    update_cache: yes
  become: true
  vars:
    packages:
      - cowsay
      - htop
      - hugepages
      - iftop
      - libffi-dev
      - nload
      - ntp
      - python-minimal
      - python3
      - python3-pip
      - sysstat
      - tmux
      - unzip
      - wget
      - zip

- name: Install aws commandline tools
  pip:
    name:
      - requests
      - chardet
      - urllib3
      - awscli
    executable: pip3
    state: latest
  become: true

- name: Update all packages to the latest version
  apt:
    upgrade: dist
  become: true

- name: Stop iptables
  service: name=ufw state=stopped enabled=no
  become: true

- name: Set swappiness to 0
  sysctl:
    name: vm.swappiness
    value: 0
    state: present
  become: true