apiVersion: batch/v1
kind: Job
metadata:
  name: rou-init
  labels:
    app: rou-init
spec:
  template:
    spec:
      containers:
        - name: rou-init
          image: ghcr.io/big-wave-tech/data-profiler/rou-init
          imagePullPolicy: IfNotPresent
          command: ["python", "activate_attributes.py"]
      restartPolicy: Never
  backoffLimit: 1
